# This configuration file allows our pre-commit hooks to be used with pre-commit: http://pre-commit.com/

- id: tflint
  name: tflint
  description: Linter for Terraform source code
  entry: hooks/tflint.sh
  language: script
  files: \.tf$
  exclude: \.+.terraform\/.*$
